spring:
  bot:
    plugin-list: # 配置插件列表（有序），如果插件返回0，继续执行剩余插件，如果插件返回1，终止剩余插件执行
      - net.lz1998.pbbot.plugin.LogPlugin # 日志插件
      - net.lz1998.pbbot.plugin.DemoPlugin # 测试插件
      - net.lz1998.pbbot.plugin.ImagePlugin # 动态生成图片插件
      - net.lz1998.pbbot.plugin.HelloPlugin # 测试插件
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: qq-test
    version: '@project.version@'
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  banner:
    charset: UTF-8

server:
  port: 8081

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:mapper/**/*.xml
